apiVersion: apps/v1
kind: Deployment
metadata:
  name: mq-monitor
  namespace: {{ .Values.namespace }}
  labels:
    app: mq-monitor
spec:
  selector:
    matchLabels:
      app: mq-monitor
  replicas: 1
  minReadySeconds: 10
  template:
    metadata:
      labels:
        app: mq-monitor
      annotations:
        prometheus.io/path: {{ .Values.prometheus.path }}
        prometheus.io/port: {{ .Values.prometheus.port | quote }}
        prometheus.io/scrape: 'true'
    spec:
      containers:
        - name: mq-monitor
          image: {{ .Values.deployment.image }}
          imagePullPolicy: Always
          ports:
            - containerPort: {{ .Values.deployment.container.port }}
              name: metrics
          volumeMounts:
            - mountPath: /opt/config/mq_prometheus.yaml
              subPath: mq_prometheus.yaml
              name: prometheus
              readOnly: false
      volumes:
        - name: prometheus
          configMap:
            name: mq-monitor-prometheus
            items:
              - key: mq_prometheus.yaml
                path: mq_prometheus.yaml


