apiVersion: v1
kind: Service
metadata:
  name: mq-monitoring-service
  namespace: {{ .Values.namespace }}
  labels:
    app: mq-monitor
  annotations:
    prometheus.io/path: {{ .Values.prometheus.path }}
    prometheus.io/port: metrics
    prometheus.io/scrape: 'true'
spec:
  selector:
    app: mq-monitor
  type: ClusterIP
  ports:
    - protocol: TCP
      name: metrics
      port: {{ .Values.deployment.container.port }}
      targetPort: {{ .Values.deployment.container.port }}
