apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: mq-monitor
  namespace: default
  labels:
    app: mq-monitor
spec:
  selector:
    matchLabels:
      app: mq-monitor
  namespaceSelector:
    matchNames:
      - default
  endpoints:
    - port: metrics
      path: /metrics
      interval: 15s