apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: mq-monitor-{{ .Values.monitored.seqment }}
  namespace: {{ .Values.prometheus.namespace }}
  labels:
    app: mq-monitor-{{ .Values.monitored.seqment }}
spec:
  selector:
    matchLabels:
      app: mq-monitor-{{ .Values.monitored.seqment }}
  namespaceSelector:
    matchNames:
      - {{ .Values.namespace }}
  endpoints:
    - port: {{ .Values.prometheus.port }}
      path: {{ .Values.prometheus.path }}
      interval: 15s
