apiVersion: v1
kind: Service
metadata:
  name: mq-monitoring-service-{{ .Values.monitored.seqment }}
  namespace: {{ .Values.namespace }}
  labels:
    app: mq-monitor-{{ .Values.monitored.seqment }}
  annotations:
    prometheus.io/path: {{ .Values.prometheus.path }}
    prometheus.io/port: {{ .Values.prometheus.port }}
    prometheus.io/scrape: 'true'
spec:
  selector:
    app: mq-monitor-{{ .Values.monitored.seqment }}
  type: ClusterIP
  ports:
    - protocol: TCP
      name: metrics
      port: {{ .Values.deployment.container.port }}
      targetPort: {{ .Values.deployment.container.port }}
