##
## Set general values
##

namespace: mq

monitored:
  segment: ABC

##
## Set deployment values
##

deployment:
  image: yannig/mq-metric-prometheus:5.4.0
  container:
    port: 9157

##
## Set configmap values
##

config:
  logLevel: TRACE

queueManager:
  name: testqm
  connection: 
  channel:
  user:
  password:
  queues:
  topics:

prometheus:
  port: metrics
  path: "/metrics"
  namespace: default
