##
## Set general values
##

namespace: mq

monitored:
  segment: ABC

##
## Set deployment values
##

deployment:
  image: yannig/mq-metric-prometheus:5.4.0
  container:
    port: 9157

##
## Set monitor configurations values
##

config:
  logLevel: TRACE

queueManager:
  name: testqm
  connection: mq-ibm-mq.mq(1414)
  channel: DEV.ADMIN.SVRCONN
  user: admin
  password: passw0rd
  queues:
    - APP.*
    - "!SYSTEM.*"
    - "!AMQ.*"
    - QM*
    - DEV*
  channels:
    - SYSTEM.*
    - TO.*
  topics:
  subscriptions:

##
## Set monitor prometheus configuration values
##
prometheus:
  port: metrics
  path: "/metrics"
  namespace: default
